Traducao/http server
larien/learn-go-with-tests pull request #91
Opened 2020-04-02 00:47 UTC by ehriq

Terminei a tradução e fiz uma primeira revisão do texto.

2020-04-11 23:02 UTC, fsmiamoto commented on criando-uma-aplicacao/http-server/http-server.md
> +Ótimo! Criamos um serviço de acordo com os padrões REST! Para seguirmos em frente, precisamos decidir qual o armazenamento de dados vamos usar, e um que dure mais que o tempo que o programa rodar.
Aqui acho que o autor fala num tom sugestivo, sugiro algo como:
> ... REST! Se quiser continuar, você pode escolher um armazenamento de dados com maior persistência, que não vai perder os dados quando o programa terminar.

2020-04-11 23:04 UTC, fsmiamoto commented on criando-uma-aplicacao/http-server/http-server.md
> +* Você precisa tratar falhas na compilação ou noss testes como uma situação urgente, a qual precisa resolver o mais rápido possível.
`noss` -> `nos`

2020-04-27 19:01 UTC, devdrops commented on criando-uma-aplicacao/http-server/http-server.md
> +Se tivéssemos começado com o código de armazenamento dos dados, a quantidade de alterações que precisaríamos fazer seria muito grande. **Este é um pequeno passo em relação ao nosso objetivo final e f
`guiado` ao invés de `guidado` :wink:

2020-04-27 19:04 UTC, devdrops commented on criando-uma-aplicacao/http-server/http-server.md
> +Nós movemos o cálculo de pontuação pra fora do código principal que trata a requisição (_handler_) para uma função `GetPlayerScore`. Isso parece ser o lugar correto para isolar as responsabilidades u
`para fora` ao invés de `pra fora` - não tá errado, é só pra não irritar o Pasquale mesmo :smile: 
![](https://images.uncyc.org/pt/thumb/3/38/Pasquale01.jpg/300px-Pasquale01.jpg)

2020-04-27 19:08 UTC, devdrops commented on criando-uma-aplicacao/http-server/http-server.md
> +Inicialmente vamos verificar se obtemos o status HTTP correto ao fazer a requisição em uma rota específica usando POST. Isso nos permite preparar o caminho da funcionalidade que aceita um tipo difere
`como esperado` ao invés de `como esperaodo` :wink:

2020-04-27 19:09 UTC, devdrops commented on criando-uma-aplicacao/http-server/http-server.md
> +O _handler_ parece um pouco bagunçado agora. Vamos separar o código para ficar simples de entender e isolar as diferentes funcionalidade em novas funções.
`funcionalidades` ao invés de `funcionalidade` :wink:

2020-04-27 19:13 UTC, devdrops commented on criando-uma-aplicacao/http-server/http-server.md
> +O que vamos fzer agora é escrever um _teste de integração_ entre `PlayerServer` e `InMemoryPlayerStore` para terminar a funcionalidade. Isso vai permitir confiar que a aplicação está funcionando, sem
`fazer` ao invés de `fzer` :wink:

2020-04-27 19:14 UTC, devdrops commented on criando-uma-aplicacao/http-server/http-server.md
> +Abaixo, há mais código do que que o esperado para se escrever sem ter os testes correspondentes.
`do que o esperado` ao invés de `do que que o esperado` :wink:

2020-04-27 19:15 UTC, devdrops commented on criando-uma-aplicacao/http-server/http-server.md
> +* Pra ajudar nos testes, criamos a `NewInMemoryPlayerStore` para inicializar o armazenamento, e o código do teste de integração foi atualizado para usar esta função \(`store := NewInMemoryPlayerStore
`Para ajudar` ao invés de `Pra ajudar` :wink:

2020-05-31 01:01 UTC, ehriq commented on criando-uma-aplicacao/http-server/http-server.md
> +(Nota do tradutor: A expressão _mocking_ significa "zombar", "fazer piada" ou "enganar". Mas em programação, _mocking_ significa criar _algo_, como uma classe ou função, que retorna os valores espera
pensei em colocar isso pq são expressões muito usadas na língua original. tanto que muita gente já fez aquela adaptação marota pra MOCKAR.

2020-05-31 01:03 UTC, ehriq commented on criando-uma-aplicacao/http-server/http-server.md
> +Isso faz com que a função de roteamento do `ServeHTTP` esteja mais clara, e permite que nossas próximas iterações para armazenamento possa estar dentro de `processWin`.
tentei alterar, está melhor?

2020-05-31 01:07 UTC, ehriq commented on criando-uma-aplicacao/http-server/http-server.md
> +Você recebeu o desafio de criar um servidor web para que usuários possam acompanhar quantas partidas os jogadores (players) venceram.
Eu mantive "players" porque é o usado em todo o código. Acha ruim?

2020-05-31 01:07 UTC, ehriq commented on criando-uma-aplicacao/http-server/http-server.md
> +func ListenAndServe(endereco string, handler Handler) error
Concordo.

2020-05-31 01:09 UTC, ehriq commented on criando-uma-aplicacao/http-server/http-server.md
> +Nós movemos o cálculo de pontuação pra fora do código principal que trata a requisição (_handler_) para uma função `GetPlayerScore`. Isso parece ser o lugar correto para isolar as responsabilidades u
hahahahahaha.

2020-05-31 01:21 UTC, larien commented
Ótima tradução mesmo, Erick, e muito obrigada pela sua colaboração e da galera que revisou :D

Só um ponto: na primeira tradução foi amplamente discutido se era necessário manter os termos em inglês ou se traduziríamos em português.
O consenso foi traduzir tudo para português (e se mantiver em inglês, explicar o que o termo é para facilitar para as pessoas que tão começando). O principal motivo para isso é que as pessoas que utilizam esse livro costumam ter como principal objetivo entender os conceitos por trás dos testes com Go e não nos termos em inglês e ela tem diversas outras formas de aprender esses termos em inglês.
Logo, pode por favor traduzir os termos em inglês que ficaram?
Se tiver dúvida sobre como a tradução deve ficar, só dar um toque aqui :)

No final de junho eu volto a dar apoio para as traduções :)

2020-05-31 01:27 UTC, ehriq commented
Pessoal, agradeço as revisões. E agradeço demais à @larien por ter iniciado a tradução. 

@larien eu lembro dessa discussão, inclusive participei dela; tentei manter as expressões em inglês quando realmente percebi que não conseguia uma tradução boa (por exemplo, em _mocking_), e daí coloquei uma "nota de tradutor". O que sugere que eu altere, tem algum exemplo?

E no código, altero tudo também, para expressões em pt-br?

2020-05-31 01:33 UTC, larien commented
Achei a nota de tradutor ótima, moço :D essa é a ideia mesmo, já que mock é uma palavra complicada de traduzir
Aí é isso mesmo, até no código as palavras são traduzidas :) `Server` para `Servidor`, `Store` para `Armazenamento` e essa linha

2020-05-31 20:01 UTC, ehriq commented
@larien fiz a tradução completa onde era possível. Traduzi, também, os códigos em /v[1-5]/.

2020-09-27 00:37 UTC, fsmiamoto requested changes
Quase lá!
Antes tarde do que nunca mas lá vai alguns ajustes / sugestões adicionais

2020-09-27 00:37 UTC, fsmiamoto commented on criando-uma-aplicacao/servidor-http/servidor-http.md
> +Para executar, execute o comando `go build`, que vai pegar todos os arquivos terminados em `.go` neste diretório e construir seu programa. E então você pode executar o programa rodando `./programa`.
O binário pode não se chamar `programa` e como é algo que iniciantes podem se bater, sugiro adicionarmos a flag  `-o`
```suggestion
Para executar, execute o comando `go build -o programa`, que vai pegar todos os arquivos terminados em `.go` neste diretório e construir seu programa. E então você pode executar o programa rodando `./programa`.
```

2020-09-27 00:37 UTC, fsmiamoto commented on criando-uma-aplicacao/servidor-http/servidor-http.md
> +Ainda assim, ainda não estamos felizes. Não parece correto que o servidor saiba as pontuações.
```suggestion
Ainda assim, não estamos felizes. Não parece correto que o servidor saiba as pontuações.
```

2020-09-27 00:37 UTC, fsmiamoto commented on criando-uma-aplicacao/servidor-http/servidor-http.md
> +     := r.URL.Path[len("/jogadores/"):]
```suggestion
     jogador := r.URL.Path[len("/jogadores/"):]
```

2020-09-27 00:37 UTC, fsmiamoto commented on criando-uma-aplicacao/servidor-http/servidor-http.md
> +    t.Run("returns Maria's score", func(t *testing.T) {
Vamos usar as frases em inglês aqui? 
Considerando que quase tudo está traduzido, pode ficar um pouco estranho.

2020-09-27 00:37 UTC, fsmiamoto commented on criando-uma-aplicacao/servidor-http/servidor-http.md
> +Um _mapa_ (`map`) é um jeito simples e rápido de fazer um armazenamento chave/valor para os nossos testes. Agora vamos criar um desses armazenamentos para os nosso testes e inserir em nosso `JogadorS
```suggestion
Um _mapa_ (`map`) é um jeito simples e rápido de fazer um armazenamento chave/valor para os nossos testes. Agora vamos criar um desses armazenamentos para os nossos testes e inserir em `JogadorServidor`.
```

2020-09-27 00:37 UTC, fsmiamoto commented on criando-uma-aplicacao/servidor-http/servidor-http.md
> +Precisamos fazer uma implementação de um, mas isso é difícil no momento, já que não estamos armazenando nenhum dado significativo, por isso precisará ser, por enquanto, um valor predefinido. Vamos al
```suggestion
Precisamos implementar um. Mas isso é difícil no momento, já que não estamos armazenando nenhum dado significativo e por isso vamos usar um valor predefinido, por enquanto. Vamos alterar na `main.go`:
```

2020-09-27 00:37 UTC, fsmiamoto commented on criando-uma-aplicacao/servidor-http/servidor-http.md
> +func (ja *JogadorServidor) ServeHTTP(w http.ResponseWriter, r *http.Request) {
```suggestion
func (js *JogadorServidor) ServeHTTP(w http.ResponseWriter, r *http.Request) {
```

2020-09-27 00:37 UTC, fsmiamoto commented on criando-uma-aplicacao/servidor-http/servidor-http.md
> +func (p *JogadorServidor) mostrarPontuacao(w http.ResponseWriter, r *http.Request) {
```suggestion
func (js *JogadorServidor) mostrarPontuacao(w http.ResponseWriter, r *http.Request) {
```

2020-09-27 00:37 UTC, fsmiamoto commented on criando-uma-aplicacao/servidor-http/servidor-http.md
> +	pontuacao := p.armazenamento.ObterPontuacaoJogador(jogador)
```suggestion
	pontuacao := js.armazenamento.ObterPontuacaoJogador(jogador)
```

2020-09-27 00:37 UTC, fsmiamoto commented on criando-uma-aplicacao/servidor-http/servidor-http.md
> +func (p *JogadorServidor) registrarVitoria(w http.ResponseWriter) {
```suggestion
func (js *JogadorServidor) registrarVitoria(w http.ResponseWriter) {
```

2020-09-27 00:37 UTC, fsmiamoto commented on criando-uma-aplicacao/servidor-http/servidor-http.md
> +Vamos implementar isso estendendo o `EsbocoJogadorArmazenamento` com um novo método `RecordWin` e então inspecionar as chamadas.
```suggestion
Vamos implementar isso estendendo o `EsbocoJogadorArmazenamento` com um novo método `RegistrarVitoria` e então inspecionar as chamadas.
```

2020-09-27 00:37 UTC, fsmiamoto commented on criando-uma-aplicacao/servidor-http/servidor-http.md
> +Agora que `JogadorArmazenamento` tem o método `RecordWin`, podemos chamar de dentro do nosso `JogadorServidor`
```suggestion
Agora que `JogadorArmazenamento` tem o método `RegistrarVitoria`, podemos chamar de dentro do nosso `JogadorServidor`
```

2020-09-27 00:37 UTC, fsmiamoto commented on criando-uma-aplicacao/servidor-http/servidor-http.md
> +    p.armazenamento.RecordWin("Marcela")
```suggestion
    js.armazenamento.RegistrarVitoria("Marcela")
```

2020-09-27 00:37 UTC, fsmiamoto commented on criando-uma-aplicacao/servidor-http/servidor-http.md
> +func (p *JogadorServidor) registrarVitoria(w http.ResponseWriter) {
```suggestion
func (js *JogadorServidor) registrarVitoria(w http.ResponseWriter) {
```

2020-09-27 00:37 UTC, fsmiamoto commented on criando-uma-aplicacao/servidor-http/servidor-http.md
> +Rode os testes e deve estar funcionando sem erros! Claro, `"Marcela"` não é bem o que queremos enviar para `RegistrarVitoria`, então vamos ajustar os testes.
```suggestion
Rode os testes e eles devem estar funcionando sem erros! Claro, `"Marcela"` não é bem o que queremos enviar para `RegistrarVitoria`, então vamos ajustar os testes.
```

2020-09-27 00:37 UTC, fsmiamoto commented on criando-uma-aplicacao/servidor-http/servidor-http.md
> +* Para ajudar nos testes, criamos a `NewJogadorArmazenamentoNaMemoria` para inicializar o armazenamento, e o código do teste de integração foi atualizado para usar esta função \(`armazenamento := New
```suggestion
* Para ajudar nos testes, criamos a `CriaJogadorArmazenamentoNaMemoria` para inicializar o armazenamento, e o código do teste de integração foi atualizado para usar esta função \(`armazenamento := CriaJogadorArmazenamentoNaMemoria()`\).
```

2020-09-27 00:37 UTC, fsmiamoto commented on criando-uma-aplicacao/servidor-http/servidor-http.md
> +Nosso teste de integração passa, e agora só é preciso mudar o `main` para usar o `NewJogadorArmazenamentoNaMemoria()`
```suggestion
Nosso teste de integração passa, e agora só é preciso mudar o `main` para usar o `NewJogadorArmazenamentoNaMemoria()`
```
```suggestion
Nosso teste de integração passa, e agora só é preciso mudar o `main` para usar o `CriaJogadorArmazenamentoNaMemoria()`
```

2020-09-27 00:37 UTC, fsmiamoto commented on criando-uma-aplicacao/servidor-http/servidor-http.md
> +    servidor := &JogadorServidor{CriarJogadorArmazenamentoNaMemoria()}
```suggestion
    servidor := &JogadorServidor{CriaJogadorArmazenamentoNaMemoria()}
```

2020-09-27 00:37 UTC, fsmiamoto commented on criando-uma-aplicacao/servidor-http/servidor-http.md
> +* o Desenvolvimento Orientado a Testes nos ajudou a definir as interfaces necessárias
```suggestion
* O Desenvolvimento Orientado a Testes nos ajudou a definir as interfaces necessárias
```

2020-09-27 00:37 UTC, fsmiamoto commented on criando-uma-aplicacao/servidor-http/v5/server_test.go
> +func TestStoreWins(t *testing.T) {
```suggestion
func TestRegistarVitoria(t *testing.T) {
```

2020-11-10 15:34 UTC, devdrops commented
Fala @ehriq! Tudo certo?

Precisa de alguma ajuda com este PR?

2020-12-22 15:39 UTC, devdrops commented
Salve @larien!

Precisa de ajuda neste PR?

2021-01-02 01:58 UTC, larien commented on criando-uma-aplicacao/json/json.md
>  [**You can find all the code for this chapter here**](https://github.com/quii/learn-go-with-tests/tree/master/criando-uma-aplicacao/json)
Sim, esse capítulo ainda não foi mergeado :)

2021-01-02 02:08 UTC, larien commented
Gente, muito obrigada pela tradução e pelas revisões! Apliquei todos os pontos por aqui e estou mergeando a PR.

2021-01-02 02:08 UTC, merged