WIP: Traducao/json routing and embedding
larien/learn-go-with-tests pull request #92
Opened 2020-04-28 19:48 UTC by Ronald-TR

Ainda falta traduzir os códigos, mas gostaria de deixar o PR aberto pra ser revisado.

Ps: Desculpem qualquer coisa.
Abraços!!

2020-05-13 21:00 UTC, devdrops commented on criando-uma-aplicacao/json.md
>  We can use `t.Run` to break up this test a bit and we can reuse the helpers from our server tests - again showing the importance of refactoring tests.
Trecho em en_US que foi traduzido e tá sobrando aqui :slightly_smiling_face:

2020-05-13 21:01 UTC, devdrops commented on criando-uma-aplicacao/json.md
> +Tudo que nós precisamos fazer é interar através do map e converter cada chave/valor para um `Jogador`
`iterar` ao invés de `interar` :wink:

2020-05-13 21:02 UTC, devdrops commented on criando-uma-aplicacao/json.md
> +## Enpacotando
O `Wrapping up` aqui tem um significado de "resumão" de tudo o que foi visto até aqui, então, que tal se mudarmos a tradução para `Concluindo`? :wink:

2020-05-13 21:03 UTC, devdrops commented on criando-uma-aplicacao/json.md
> +Nós temos continuado a seguramente iterar no nosso programa usando TDD, fazendo ele suportar novos endpoints de uma forma manutenivel com um roteador e isso pode agora retornar JSON para nossos consu
`manutenível` ao invés de `manutenivel` :wink:

2020-05-13 21:04 UTC, devdrops commented on criando-uma-aplicacao/json.md
> +* **Composição**. Nós tocamos um pouco nesta tecnica porém você pode [ler mais sobre isso de Effective Go](https://golang.org/doc/effective_go.html#embedding). Se há uma coisa que você deve tirar dis
`técnica` ao invés de `tecnica` :wink:

2020-05-13 21:07 UTC, devdrops commented on criando-uma-aplicacao/json.md
> +* **JSON desserialização e serialização**. A biblioteca padrão faz isto de forma bastante trivial ao serializar e desserializar nosso dado. Isto também abre para configurações e você pode customizar
`Serialização e Desserialização de JSON` ao invés de `JSON desserialização e serialização` :wink:

2020-11-10 15:33 UTC, devdrops commented
Fala @Ronald-TR! Tudo certo?

Precisa de alguma ajuda com este PR?

2020-12-22 15:39 UTC, devdrops commented
Salve @larien!

Precisa de ajuda neste PR?

2020-12-22 23:34 UTC, Ronald-TR commented on criando-uma-aplicacao/json.md
> +* **JSON desserialização e serialização**. A biblioteca padrão faz isto de forma bastante trivial ao serializar e desserializar nosso dado. Isto também abre para configurações e você pode customizar
Done!

2020-12-22 23:34 UTC, Ronald-TR commented on criando-uma-aplicacao/json.md
> +* **Composição**. Nós tocamos um pouco nesta tecnica porém você pode [ler mais sobre isso de Effective Go](https://golang.org/doc/effective_go.html#embedding). Se há uma coisa que você deve tirar dis
Done!

2020-12-22 23:34 UTC, Ronald-TR commented on criando-uma-aplicacao/json.md
> +Nós temos continuado a seguramente iterar no nosso programa usando TDD, fazendo ele suportar novos endpoints de uma forma manutenivel com um roteador e isso pode agora retornar JSON para nossos consu
Done!

2020-12-22 23:34 UTC, Ronald-TR commented on criando-uma-aplicacao/json.md
> +## Enpacotando
Done!

2020-12-22 23:34 UTC, Ronald-TR commented on criando-uma-aplicacao/json.md
> +Tudo que nós precisamos fazer é interar através do map e converter cada chave/valor para um `Jogador`
Done!

2020-12-22 23:35 UTC, Ronald-TR commented on criando-uma-aplicacao/json.md
> +Go têm um mecanismo de rotas nativo (built-in) chamado [`ServeMux`](https://golang.org/pkg/net/http/#ServeMux) \(request multiplexer\) que nos permite atracar um `http.Handler`s para caminhos de uma
Done!

2020-12-22 23:35 UTC, Ronald-TR commented on criando-uma-aplicacao/json.md
> +Antes de nos preocuparmos sobre as pontuações atuais e o JSON, nós vamos tentar manter as mudanças pequenas com o plano de ir passo a passo rumo ao nosso objetivo. O inicio mais simples é checar se n
Done!

2020-12-22 23:35 UTC, Ronald-TR commented on criando-uma-aplicacao/json.md
> +[No capítulo anterior](http-server.md) nós criamos um web server para armazenar quantos jogos nossos jogadores venceram.
Done!

2020-12-22 23:35 UTC, Ronald-TR commented on criando-uma-aplicacao/json.md
> +[**Você pode encontrar todo o código para este capítulo aqui**](https://github.com/quii/learn-go-with-tests/tree/master/json)
Done!

2020-12-22 23:35 UTC, Ronald-TR commented on criando-uma-aplicacao/json.md
>  # JSON, roteamento and embedding
Done!

2020-12-22 23:43 UTC, Ronald-TR commented on criando-uma-aplicacao/json.md
> +* Para a rota `/players/` nós somente recortamos e colamos nosso codigo dentro de outro `http.HandlerFunc`.
Done!

2020-12-22 23:44 UTC, Ronald-TR commented on criando-uma-aplicacao/json.md
> +É um pouco estranho \(e ineficiente\) estar configurando um router quando uma requisição chegar e então chama-lo. O que idealmente queremos fazer é uma função do tipo `NewPlayerServer` que pegará nos
Done!

2020-12-22 23:44 UTC, Ronald-TR commented on criando-uma-aplicacao/json.md
> +finalmente, se certifique de que você **deletou** `func (p *PlayerServer) ServeHTTP(w http.ResponseWriter, r *http.Request)` por não ser mais necessária!
Done!

2020-12-22 23:44 UTC, Ronald-TR commented on criando-uma-aplicacao/json.md
> +        todo, fiquei sem saber como traduzir este trecho abaixo:
Obrigado pela sugestão, a adotei haha!

2020-12-22 23:44 UTC, Ronald-TR commented on criando-uma-aplicacao/json.md
> +Para "preencher" o `http.Handler` nós atribuimos ele para o `router` que nós criamos em `NewPlayerServer`. Nós podemos fazer isso porque `http.ServeMux` tem o método `ServeHTTP`.
Done!

2020-12-22 23:44 UTC, Ronald-TR commented on criando-uma-aplicacao/json.md
> +Nós poderíamos retornar um JSON semelhante a este:
Done!

2020-12-22 23:44 UTC, Ronald-TR commented on criando-uma-aplicacao/json.md
> +Nós vamos começar tentando analizar a resposta dentro de algo mais significativo.
Done!

2020-12-22 23:44 UTC, Ronald-TR commented on criando-uma-aplicacao/json.md
> +`Decode` pega o endereço da coisa que nós estamos tentando decodificar, e é por isso que nós declaramos uma fatia vazia de `Jogador` na linha anterior.
Done!

2020-12-22 23:44 UTC, Ronald-TR commented on criando-uma-aplicacao/json.md
> +Note que nós exibimos que o corpo da resposta junto com o erro, pois é importante para qualquer outra pessoa que esteja rodando os testes ver que o texto não pôde ser analisado.
Done!

2020-12-22 23:45 UTC, Ronald-TR commented on criando-uma-aplicacao/json.md
> +Atualize `StubPlayerStore` para permitir que ele armazene uma liga, que é apenas uma fatia de `Jogador`. Nós vamos armazenar nossos dados esperados lá.
Done!

2020-12-22 23:45 UTC, Ronald-TR commented on criando-uma-aplicacao/json.md
> +Tente rodando os testes novamente e você deverá ter:
Done!

2020-12-22 23:45 UTC, Ronald-TR commented on criando-uma-aplicacao/json.md
> +Tente rodando os testes novamente e você deverá ter:
Done!

2020-12-22 23:45 UTC, Ronald-TR commented on criando-uma-aplicacao/json.md
> +## Escreva código suficiente para faze-lo passar
Done!

2020-12-22 23:45 UTC, Ronald-TR commented on criando-uma-aplicacao/json.md
> +Tente e rode os testes:
Done!

2020-12-22 23:45 UTC, Ronald-TR commented on criando-uma-aplicacao/json.md
> +Tente e rode os testes, o compilador deve passar e os testes deverão estar passando!
Done!

2020-12-22 23:45 UTC, Ronald-TR commented on criando-uma-aplicacao/json.md
> +O código de teste não transmite suas intensões muito bem e possui vários trechos que podem ser refatorados.
Done!

2020-12-22 23:45 UTC, Ronald-TR commented on criando-uma-aplicacao/json.md
> +Nós podemos usar `t.Run` para parar este teste um pouco e então reusar os helpers dos testes do nosso servidor - novamente mostrando a importancia de refatoração dos testes.
Done!

2020-12-22 23:46 UTC, Ronald-TR commented on criando-uma-aplicacao/json.md
>  We can use `t.Run` to break up this test a bit and we can reuse the helpers from our server tests - again showing the importance of refactoring tests.
Done!

2020-12-22 23:51 UTC, Ronald-TR commented
Pessoal, desculpas não são suficientes, eu literalmente esqueci de resolver as revisões, deixei a bomba e sumi. Sorry!
Subi as correções solicitadas, requisitei novamente o review, espero não ter deixado nenhuma requisição de mudança passar batido!

Cheers!

2020-12-27 00:48 UTC, larien commented
@Ronald-TR oxe, moço, todo mundo deu uma pausa esse ano, inclusive eu! Te preocupa não, o importante é que tamo de volta :) logo mais eu dou uma olhada na sua PR quando fechar as mais antigas
Obrigada novamente pelo trampo foda!

2020-12-28 15:28 UTC, devdrops requested changes
@Ronald-TR meus parabéns e muito obrigado pela tradução! :tada: 

Deixei algumas observações, e também peço que veja o seguinte ponto: alguns trechos de código exibem o nome `quii` ao invés de `larien`. Você pode corrigir isso usando o seguinte comando (requer sed):

```
sed -i 's/quii/larien/g' ./criando-uma-aplicacao/json/json.md
```

Se precisar de alguma ajuda, basta dar um salve ok? :wink:

2020-12-28 15:28 UTC, devdrops commented on criando-uma-aplicacao/json/json.md
> +Você vai precisar atualizar os outros testes, assim como nós temos um novo campo em `StubPlayerStore`; ponha-o como nulo para os outros testes.
Talvez seja interessante manter a palavra `nil` ao invés de `null`, para manter a palavra reservada da linguagem.

Pode parecer purismo (o que não deixa de ser verdade :sweat_smile:), por isso pergunto: o que acha?

2020-12-28 15:28 UTC, devdrops commented on criando-uma-aplicacao/json/json.md
>  `InMemoryPlayerStore` is returning `nil` when you call `GetLeague()` so we'll need to fix that.
Sobrou este trecho em en_US :wink:

2021-01-02 02:20 UTC, larien commented
Oi! Passando para avisar que falta só esse capítulo para a tradução principal e vou colocar minhas mãos nele muitíssimo em breve. Agradeço desde já o esforço de vocês, viu? Cês são uns lindo <3

2021-01-03 00:03 UTC, larien approved these changes
Aprovando com as correções aplicadas e códigos traduzidos :)

2021-01-03 00:05 UTC, merged