translate io chapter
larien/learn-go-with-tests pull request #99
Opened 2020-09-01 00:22 UTC by wps13

Closes #25 
Reopened PR because of _unknown repository_ problem (Original PR: #76 )

2020-09-01 15:51 UTC, devdrops commented
Muito obrigado @wps13 ! Vou revisar aqui e já dou resposta :wink:

2020-11-09 18:38 UTC, devdrops requested changes
@wps13 primeiramente, muito obrigado por reabrir este PR! Eu imagino o trabalho que deu e que você dedicou, muito obrigado mesmo por todo esse esforço!

Fiz algumas anotações de mudanças pequenas para se fazer. Se precisar de alguma ajuda, basta avisar!

---

# REVISÃO

1. Substituir os links do repo original (https://github.com/quii/learn-go-with-tests) pelo repo traduzido (https://github.com/larien/learn-go-with-tests). Você pode executar o seguinte comando para fazer isso (requer `grep`, `xargs` e `sed`):

```bash
grep -lRZ quii ./criando-uma-aplicacao/io | xargs -0 -l sed -i -e 's/quii/larien/g'
```

2. Executar um `go fmt` nos arquivos. Você pode fazer isso com o seguinte comando:

```bash
# Se você usa Docker:
docker run --rm -v $(pwd):/code -w /code golang:latest go fmt ./criando-uma-aplicacao/io/...

# Se não usa Docker:
go fmt ./criando-uma-aplicacao/io/...
```

3. No arquivo `criando-uma-aplicacao/io/v2/SistemaDeArquivoDeArmazenamentoDoJogador_test.go`, linha 27, o comentário ainda está em en_US :wink:

4. Alguns arquivos declararam a função `defineCorpoDeReposta`, faltando um `s` para a palavra _Resposta_. Você pode corrigir isso executando o seguinte comando (requer `grep`, `xargs` e `sed`):

```bash
grep -lRZ defineCorpoDeReposta ./criando-uma-aplicacao/io | xargs -0 -l sed -i -e 's/defineCorpoDeReposta/defineCorpoDeResposta/g'
```

5. No arquivo `criando-uma-aplicacao/io/v3/SistemaDeArquivoDeArmazenamentoDoJogador.go`, linha 20, o comentário ainda está em en_US :wink:

6. Nos arquivos `criando-uma-aplicacao/io/v5/integracao_servidor_test.go`, `criando-uma-aplicacao/io/v6/integracao_servidor_test.go`, `criando-uma-aplicacao/io/v7/integracao_servidor_test.go`, `criando-uma-aplicacao/io/v8/integracao_servidor_test.go` e `criando-uma-aplicacao/io/v9/integracao_servidor_test.go`, tem um comentário em en_US que faltou traduzir. Você pode resolver com o comando abaixo (requer `grep`, `xargs` e `sed`):

```bash
grep -lRZ '"get score"' ./criando-uma-aplicacao/io | xargs -0 -l sed -i -e 's/get score/pega pontuação/g'
```

2020-11-12 00:04 UTC, wps13 commented
> @wps13 primeiramente, muito obrigado por reabrir este PR! Eu imagino o trabalho que deu e que você dedicou, muito obrigado mesmo por todo esse esforço!
> 
> Fiz algumas anotações de mudanças pequenas para se fazer. Se precisar de alguma ajuda, basta avisar!
> # REVISÃO
> 
>     1. Substituir os links do repo original (https://github.com/quii/learn-go-with-tests) pelo repo traduzido (https://github.com/larien/learn-go-with-tests). Você pode executar o seguinte comando para fazer isso (requer `grep`, `xargs` e `sed`):
> 
> 
> ```shell
> grep -lRZ quii ./criando-uma-aplicacao/io | xargs -0 -l sed -i -e 's/quii/larien/g'
> ```
> 
>     1. Executar um `go fmt` nos arquivos. Você pode fazer isso com o seguinte comando:
> 
> 
> ```shell
> # Se você usa Docker:
> docker run --rm -v $(pwd):/code -w /code golang:latest go fmt ./criando-uma-aplicacao/io/...
> 
> # Se não usa Docker:
> go fmt ./criando-uma-aplicacao/io/...
> ```
> 
>     1. No arquivo `criando-uma-aplicacao/io/v2/SistemaDeArquivoDeArmazenamentoDoJogador_test.go`, linha 27, o comentário ainda está em en_US wink
> 
>     2. Alguns arquivos declararam a função `defineCorpoDeReposta`, faltando um `s` para a palavra _Resposta_. Você pode corrigir isso executando o seguinte comando (requer `grep`, `xargs` e `sed`):
> 
> 
> ```shell
> grep -lRZ defineCorpoDeReposta ./criando-uma-aplicacao/io | xargs -0 -l sed -i -e 's/defineCorpoDeReposta/defineCorpoDeResposta/g'
> ```
> 
>     1. No arquivo `criando-uma-aplicacao/io/v3/SistemaDeArquivoDeArmazenamentoDoJogador.go`, linha 20, o comentário ainda está em en_US wink
> 
>     2. Nos arquivos `criando-uma-aplicacao/io/v5/integracao_servidor_test.go`, `criando-uma-aplicacao/io/v6/integracao_servidor_test.go`, `criando-uma-aplicacao/io/v7/integracao_servidor_test.go`, `criando-uma-aplicacao/io/v8/integracao_servidor_test.go` e `criando-uma-aplicacao/io/v9/integracao_servidor_test.go`, tem um comentário em en_US que faltou traduzir. Você pode resolver com o comando abaixo (requer `grep`, `xargs` e `sed`):
> 
> 
> ```shell
> grep -lRZ '"get score"' ./criando-uma-aplicacao/io | xargs -0 -l sed -i -e 's/get score/pega pontuação/g'
> ```

Beleza, vou corrigir!

2020-11-15 17:48 UTC, devdrops requested changes
Oi @wps13 ! Muito obrigado pelas correções! Acho que só faltou o passo do `go fmt`, de resto todos os outros pontos foram corrigidos :+1: 

Você pode fazer isso com o seguinte comando:

```bash
# Se você usa Docker:
docker run --rm -v $(pwd):/code -w /code golang:latest go fmt ./criando-uma-aplicacao/io/...

# Se não usa Docker:
go fmt ./criando-uma-aplicacao/io/...
```

2020-11-15 19:24 UTC, wps13 commented
@devdrops executei o comando, só tá falhando no ci, não sei por que

2020-11-16 13:16 UTC, devdrops commented
@wps13 vendo no [Trevas](https://travis-ci.org/github/larien/learn-go-with-tests/jobs/743793076) (hehe), tem alguns erros apontados pelo `golint`:

```
$ ./build.sh
# github.com/larien/learn-go-with-tests/criando-uma-aplicacao/io/v2
criando-uma-aplicacao/io/v2/SistemaDeArquivoDeArmazenamentoDoJogador_test.go:30:3: expected declaration, found ')'
FAIL	github.com/larien/learn-go-with-tests/criando-uma-aplicacao/io/v2 [setup failed]
ok  	github.com/larien/learn-go-with-tests/criando-uma-aplicacao/command-line/v1	0.014s
?   	github.com/larien/learn-go-with-tests/criando-uma-aplicacao/command-line/v1/cmd/cli	[no test files]
?   	github.com/larien/learn-go-with-tests/criando-uma-aplicacao/command-line/v1/cmd/webserver	[no test files]
ok  	github.com/larien/learn-go-with-tests/criando-uma-aplicacao/command-line/v2	0.007s
?   	github.com/larien/learn-go-with-tests/criando-uma-aplicacao/command-line/v2/cmd/cli	[no test files]
?   	github.com/larien/learn-go-with-tests/criando-uma-aplicacao/command-line/v2/cmd/webserver	[no test files]
ok  	github.com/larien/learn-go-with-tests/criando-uma-aplicacao/command-line/v3	0.013s
?   	github.com/larien/learn-go-with-tests/criando-uma-aplicacao/command-line/v3/cmd/cli	[no test files]
?   	github.com/larien/learn-go-with-tests/criando-uma-aplicacao/command-line/v3/cmd/webserver	[no test files]
ok  	github.com/larien/learn-go-with-tests/criando-uma-aplicacao/http-server/v1	0.003s
ok  	github.com/larien/learn-go-with-tests/criando-uma-aplicacao/http-server/v2	0.010s
ok  	github.com/larien/learn-go-with-tests/criando-uma-aplicacao/http-server/v3	0.003s
ok  	github.com/larien/learn-go-with-tests/criando-uma-aplicacao/http-server/v4	0.004s
# github.com/larien/learn-go-with-tests/criando-uma-aplicacao/io/v1 [github.com/larien/learn-go-with-tests/criando-uma-aplicacao/io/v1.test]
criando-uma-aplicacao/io/v1/main.go:9:36: undefined: SalvaNovoJogadorNaMemoria
criando-uma-aplicacao/io/v1/servidor.go:73:17: p.armazenamento.RecordeDeVitorias undefined (type GuardaJogador has no field or method RecordeDeVitorias)
criando-uma-aplicacao/io/v1/integracao_servidor_test.go:10:19: undefined: NewInMemoryPlayerStore
criando-uma-aplicacao/io/v1/integracao_servidor_test.go:20:32: undefined: newGetScoreRequest
criando-uma-aplicacao/io/v1/servidor_test.go:158:28: cannot refer to unexported name http.requisicao
criando-uma-aplicacao/io/v1/servidor_test.go:158:28: undefined: http.requisicao
criando-uma-aplicacao/io/v1/servidor_test.go:163:48: cannot refer to unexported name http.requisicao
criando-uma-aplicacao/io/v1/servidor_test.go:163:48: undefined: http.requisicao
criando-uma-aplicacao/io/v1/servidor_test.go:168:47: cannot refer to unexported name http.requisicao
criando-uma-aplicacao/io/v1/servidor_test.go:168:47: undefined: http.requisicao
criando-uma-aplicacao/io/v1/integracao_servidor_test.go:20:32: too many errors
# github.com/larien/learn-go-with-tests/criando-uma-aplicacao/io/v3 [github.com/larien/learn-go-with-tests/criando-uma-aplicacao/io/v3.test]
criando-uma-aplicacao/io/v3/ArmazenamentoDeJogadorNaMemoria.go:14:54: undefined: League
criando-uma-aplicacao/io/v3/SistemaDeArquivoDeArmazenamentoDoJogador.go:15:16: f.bancoDeDados.Seek undefined (type io.Reader has no field or method Seek)
criando-uma-aplicacao/io/v3/SistemaDeArquivoDeArmazenamentoDoJogador.go:23:25: f.PegaLiga().Find undefined (type Liga has no field or method Find)
criando-uma-aplicacao/io/v3/SistemaDeArquivoDeArmazenamentoDoJogador.go:35:17: liga.Find undefined (type Liga has no field or method Find)
criando-uma-aplicacao/io/v3/servidor_test.go:132:28: cannot refer to unexported name http.requisicao
criando-uma-aplicacao/io/v3/servidor_test.go:132:28: undefined: http.requisicao
criando-uma-aplicacao/io/v3/servidor_test.go:137:48: cannot refer to unexported name http.requisicao
criando-uma-aplicacao/io/v3/servidor_test.go:137:48: undefined: http.requisicao
criando-uma-aplicacao/io/v3/servidor_test.go:142:47: cannot refer to unexported name http.requisicao
criando-uma-aplicacao/io/v3/servidor_test.go:142:47: undefined: http.requisicao
criando-uma-aplicacao/io/v3/SistemaDeArquivoDeArmazenamentoDoJogador.go:35:17: too many errors
# github.com/larien/learn-go-with-tests/criando-uma-aplicacao/io/v4 [github.com/larien/learn-go-with-tests/criando-uma-aplicacao/io/v4.test]
criando-uma-aplicacao/io/v4/ArmazenamentoDeJogadorNaMemoria.go:14:54: undefined: League
criando-uma-aplicacao/io/v4/SistemaDeArquivoDeArmazenamentoDoJogador.go:10:15: undefined: io.ReaderWriteSeeker
criando-uma-aplicacao/io/v4/servidor_test.go:158:28: cannot refer to unexported name http.requisicao
criando-uma-aplicacao/io/v4/servidor_test.go:163:48: cannot refer to unexported name http.requisicao
criando-uma-aplicacao/io/v4/servidor_test.go:168:47: cannot refer to unexported name http.requisicao
# github.com/larien/learn-go-with-tests/criando-uma-aplicacao/io/v5 [github.com/larien/learn-go-with-tests/criando-uma-aplicacao/io/v5.test]
criando-uma-aplicacao/io/v5/SistemaDeArquivoDeArmazenamentoDoJogador.go:10:15: undefined: io.ReaderWriteSeeker
criando-uma-aplicacao/io/v5/servidor_test.go:158:28: cannot refer to unexported name http.requisicao
criando-uma-aplicacao/io/v5/servidor_test.go:163:48: cannot refer to unexported name http.requisicao
criando-uma-aplicacao/io/v5/servidor_test.go:168:47: cannot refer to unexported name http.requisicao
# github.com/larien/learn-go-with-tests/criando-uma-aplicacao/io/v6 [github.com/larien/learn-go-with-tests/criando-uma-aplicacao/io/v6.test]
criando-uma-aplicacao/io/v6/SistemaDeArquivoDeArmazenamentoDoJogador.go:10:15: undefined: io.ReaderWriteSeeker
criando-uma-aplicacao/io/v6/servidor_test.go:158:28: cannot refer to unexported name http.requisicao
criando-uma-aplicacao/io/v6/servidor_test.go:163:48: cannot refer to unexported name http.requisicao
criando-uma-aplicacao/io/v6/servidor_test.go:168:47: cannot refer to unexported name http.requisicao
# github.com/larien/learn-go-with-tests/criando-uma-aplicacao/io/v7 [github.com/larien/learn-go-with-tests/criando-uma-aplicacao/io/v7.test]
criando-uma-aplicacao/io/v7/SistemaDeArquivoDeArmazenamentoDoJogador.go:20:39: cannot use fita literal (type *fita) as type io.Writer in argument to json.NewEncoder:
	*fita does not implement io.Writer (missing Write method)
criando-uma-aplicacao/io/v7/SistemaDeArquivoDeArmazenamentoDoJogador.go:33:19: f.liga.Find undefined (type Liga has no field or method Find)
criando-uma-aplicacao/io/v7/SistemaDeArquivoDeArmazenamentoDoJogador.go:44:19: f.liga.Find undefined (type Liga has no field or method Find)
criando-uma-aplicacao/io/v7/main.go:18:59: cannot convert db (type *os.File) to type SistemaDeArquivoDeArmazenamentoDoJogador
criando-uma-aplicacao/io/v7/servidor_test.go:158:28: cannot refer to unexported name http.requisicao
criando-uma-aplicacao/io/v7/servidor_test.go:158:28: undefined: http.requisicao
criando-uma-aplicacao/io/v7/servidor_test.go:163:48: cannot refer to unexported name http.requisicao
criando-uma-aplicacao/io/v7/servidor_test.go:163:48: undefined: http.requisicao
criando-uma-aplicacao/io/v7/servidor_test.go:168:47: cannot refer to unexported name http.requisicao
criando-uma-aplicacao/io/v7/servidor_test.go:168:47: undefined: http.requisicao
criando-uma-aplicacao/io/v7/main.go:18:59: too many errors
# github.com/larien/learn-go-with-tests/criando-uma-aplicacao/io/v8 [github.com/larien/learn-go-with-tests/criando-uma-aplicacao/io/v8.test]
criando-uma-aplicacao/io/v8/SistemaDeArquivoDeArmazenamentoDoJogador.go:18:9: undefined: initialisePlayeriniciaArquivoBDDoJogadorDBFile
criando-uma-aplicacao/io/v8/SistemaDeArquivoDeArmazenamentoDoJogador.go:31:39: cannot use fita literal (type *fita) as type io.Writer in argument to json.NewEncoder:
	*fita does not implement io.Writer (missing Write method)
criando-uma-aplicacao/io/v8/SistemaDeArquivoDeArmazenamentoDoJogador.go:61:19: f.liga.Find undefined (type Liga has no field or method Find)
criando-uma-aplicacao/io/v8/SistemaDeArqui [...]

2020-11-16 14:20 UTC, wps13 commented
@devdrops beleza, vou olhar cada um deles. Valeu!

2020-11-23 15:53 UTC, devdrops approved these changes
Parabéns @wps13 !!

![](https://cultofthepartyparrot.com/parrots/hd/dealwithitnowparrot.gif)

Muito obrigado pela paciência e trabalho dedicados aqui :heart:

2020-11-23 16:06 UTC, wps13 commented
valeu @devdrops :smile:

2020-12-19 17:10 UTC, larien approved these changes
Cara, foda DEMAIS! O esforço que cê deve ter tido pra traduzir um capítulo envolvendo 138 arquivos foi simplesmente foda.  Cê merece um prêmio!

2020-12-19 17:11 UTC, merged